name: Update Sitemap

on:
  schedule:
    - cron: '0 0 */30 * *'  # Run every 30 days
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Update sitemap
        run: npm run update-sitemap
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/sitemap.xml
          git commit -m "Update sitemap dates" || echo "No changes to commit"
          git push 